#+ endpoint: https://druid.datalegend.net/IISG/HISCO/sparql/HISCO
#+ tags:
#+   - regexCoding
#+ defaults:
#+   - label: adv
#+   - lang: nl

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hisco-code: <https://iisg.amsterdam/resource/hisco/code/hisco/>
SELECT * WHERE {
  ?s schema:occupationalCategory ?category .
  ?category schema:codeValue ?code .
  ?s schema:name ?name .
  FILTER(lang(?name) = "?_lang") . # filter on a given language, like "es", "nl", "se"
  FILTER regex(?name, "^?_label", "i")
  } 
ORDER BY ASC(?_name_nl)
LIMIT 1 #NB: there may be multiple correct and more correct alternatives!
